#!/usr/bin/env expect -f
spawn "./vm.py" challenge.bin

expect "do\?"

send "take tablet\r"
send "use tablet\r"
send "doorway\r"
send "north\r"
send "north\r"
send "bridge\r"
send "continue\r"
send "down\r"
send "east\r"
send "take empty lantern\r"
send "west\r"
send "west\r"
send "passage\r"
send "ladder\r"
send "west\r"
send "south\r"
send "north\r"
send "take can\r"
send "use can\r"
send "use lantern\r"
send "west\r"
send "ladder\r"
send "darkness\r"
send "continue\r"
send "west\r"
send "west\r"
send "west\r"
send "west\r"
send "north\r"
send "take red coin\r"
send "north\r"
send "east\r"
send "take concave coin\r"
send "down\r"
send "take corroded coin\r"
send "up\r"
send "west\r"
send "west\r"
send "take blue coin\r"
send "up\r"
send "take shiny coin\r"
send "down\r"
send "east\r"
send "use blue coin\r"
send "use red coin\r"
send "use shiny coin\r"
send "use concave coin\r"
send "use corroded coin\r"
send "north\r"
send "take teleporter\r"
send "use teleporter\r"
send "take business card\r"
send "take strange book\r"

# Hack teleporter "safety check"
send "fix_teleporter\r"
send "use teleporter\r"

send "west\r"
send "north\r"
send "north\r"
send "north\r"
send "north\r"
send "north\r"
send "north\r"
send "north\r"
send "east\r"
send "take journal\r"
send "west\r"
send "north\r"
send "north\r"

# Hack math "equation"
send "fix_orb\r"
send "take orb\r"
send "east\r"
send "east\r"
send "east\r"
send "north\r"
send "north\r"
send "north\r"
send "vault\r"

send "take mirror\r"
send "use mirror\r"

interact